# Generated by Django 5.0.3 on 2024-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_chessplayers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_database_admin",
            field=models.BooleanField(default=False),
        ),
    ]
