# Generated by Django 5.0.3 on 2024-03-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_user_is_database_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="Название")),
            ],
        ),
        migrations.AlterField(
            model_name="chessplayers",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="players.region"
            ),
        ),
    ]
