# Generated by Django 5.0.3 on 2024-05-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_region_alter_chessplayers_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessplayers",
            name="fide_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
